POST http://localhost:3001/register
Content-Type: application/json

{
    "first_name": "Atarhe",
    "last_name": "Ekedayen",
    "email": "atarhe@e.com",
    "password": "atarhee"
}

###
POST http://localhost:3001/login
Content-Type: application/json

{
    "email": "eruba@e.com",
    "password": "erubae"
}

###
GET http://localhost:3001/refresh

###
GET http://localhost:3001/logout
###
POST http://localhost:3001/create-chat
Content-Type: application/json

{
    "origin": "test@test.com",
    "recipient": "eruba@e.com"
}

###
GET http://localhost:3001/get-chats/eruba@e.com
###
POST http://localhost:3001/send
Content-Type: application/json

{
    "id": "89c777b9-6061-49c2-a432-a425ff9154d6",
    "topic": "Hello test",
    "sent_by": "eruba@e.com"
}
###
GET http://localhost:3001/get-messages/89c777b9-6061-49c2-a432-a425ff9154d6