POST http://localhost:3001/register
Content-Type: application/json

{
    "first_name": "Eruba",
    "last_name": "Ekedayen",
    "email": "eruba@e.com",
    "password": "erubae"
}

###
POST http://localhost:3001/login
Content-Type: application/json

{
    "email": "eruba@e.com",
    "password": "erubae"
}

###
GET http://localhost:3001/refresh

###
GET http://localhost:3001/logout
###

GET http://localhost:3001/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im0uYW5nZWxvQGdtYWlsLmNvbSIsIm5hbWUiOiJNaWtlIiwiaWF0IjoxNjg1OTYwODE4LCJleHAiOjE2ODU5NjE3MTh9.aXCiZjfjNs4L8iDWdx6UGr2hYN31FXmOfCc4bKtZw_Q